server:
  port: 0

spring:
  application:
    name: user-service

  profiles:
    active: DB

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true