spring:
  profiles:
    active: DB

  # mysql
  datasource:
    url: ${DB.url}
    username: ${DB.username_}
    password: ${DB.password}
    driver-class-name: ${DB.driver}

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  application:
    name: user-service


server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
