server:
  port: 0

spring:
  application:
    name: user-service

  profiles:
    active: DB

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672 # 대시보드 포트 X 엔진 포트 O

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true