server:
  port: 0

spring:
  profiles:
    active: DB

  # mysql
  datasource:
    url: ${DB.url}
    username: ${DB.username_}
    password: ${DB.password}
    driver-class-name: ${DB.driver}

# JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  application:
    name: order-service
