server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
#          uri: file://C:\dev\secret
          uri: https://github.com/ojs258/ConfigRepository.git